language: go
go:
  - 1.5.2

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin

script: ginkgo -coverpkg github.com/chrisehlen/knex test
